# Generated by Django 6.0.1 on 2026-01-15 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='is_disabled_friendly',
            field=models.BooleanField(default=False, verbose_name='For disabled'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_number',
            field=models.CharField(max_length=10, verbose_name='Spot number'),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Zone name'),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price per hour'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspot', verbose_name='Spot'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
